# Generated by Django 5.0.1 on 2024-01-10 22:41

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назавние')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('publicated_at', models.DateField(verbose_name='Дата публикации')),
                ('deleted_at', models.DateField(verbose_name='Дата удаления')),
                ('updated_at', models.DateField(verbose_name='Дата обновления')),
                ('request_at', models.DateField(auto_now_add=True, verbose_name='Дата запроса на публикацию')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('backup_photo', models.ImageField(upload_to='', verbose_name='Фотография до изменения')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='models_app.categories', verbose_name='Категория')),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='models_app.status', verbose_name='Статус')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='models_app.users', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='models_app.photo', verbose_name='Фотография')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='models_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publicated_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('reply_id', models.IntegerField(verbose_name='Ответ на комментарий')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='models_app.photo', verbose_name='Фотография')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='models_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models_app.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models_app.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
