# Generated by Django 5.0.1 on 2024-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('на модерации', 'На модерации'), ('одобренно', 'Одобрено'), ('на удалении', 'На удалении')], default='на модерации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply_id',
            field=models.IntegerField(null=True, verbose_name='Ответ на комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='backup_photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография до изменения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deleted_at',
            field=models.DateField(null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='publicated_at',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateField(null=True, verbose_name='Дата обновления'),
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
