# Generated by Django 5.0.1 on 2024-01-31 15:59

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_photo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=django_fsm.FSMField(choices=[('Moderation', 'moderation'), ('Published', 'published'), ('Reject', 'reject'), ('Delete', 'delete')], default='Moderation', max_length=50),
        ),
    ]
