# Generated by Django 5.0.1 on 2024-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='scheduled_deletion_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
