# Generated by Django 5.0.3 on 2024-03-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_rename_category_id_photo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
