# Generated by Django 5.0.3 on 2024-03-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_rename_photo_id_comments_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reply_id',
            new_name='reply',
        ),
    ]
