# Generated by Django 5.0.2 on 2024-02-19 10:51

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_request_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса на публикацию'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='publicated_at',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=django_fsm.FSMField(choices=[('Moderation', 'Модерация'), ('Published', 'Опубликовано'), ('Reject', 'Отклонено'), ('Delete', 'Удаление')], default='Moderation', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Дата обновления'),
        ),
    ]
