# Generated by Django 5.0.3 on 2024-03-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_user_options_alter_photo_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category_id',
            new_name='category',
        ),
    ]
