# Generated by Django 5.0.3 on 2024-03-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_rename_user_id_photo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='liked',
            old_name='user_id',
            new_name='user',
        ),
    ]
