# Generated by Django 5.0.3 on 2024-03-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_rename_photo_id_liked_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
